deploy:
  provider: releases
  api_key: $APIKEY
  file: ULE.ELF
  skip_cleanup: true
  on:
tags: true

sudo: required

install:
 ## Dependencies
- sudo apt-get install -yqqq gcc-4.4 patch wget make git libc6-dev zlib1g zlib1g-dev libucl1 libucl-dev
 ## ps2dev

before_script:
- export PS2DEV=${HOME}/ps2dev
- export PS2SDK=${PS2DEV}/ps2sdk
- export PATH=${PATH}:${PS2DEV}/bin:${PS2DEV}/ee/bin:${PS2DEV}/iop/bin:${PS2DEV}/dvp/bin:${PS2SDK}/bin
- git clone https://github.com/ps2dev/ps2toolchain.git
- cd ps2toolchain/
- git checkout 9d1d184
- travis_wait 60 bash ./toolchain.sh 1 > /tmp/PS2TOOLCHAIN1.log 2>&1
- travis_wait 60 bash ./toolchain.sh 2 > /tmp/PS2TOOLCHAIN2.log 2>&1
- travis_wait 60 bash ./toolchain.sh 3 > /tmp/PS2TOOLCHAIN3.log 2>&1
- travis_wait 60 bash ./toolchain.sh 4 > /tmp/PS2TOOLCHAIN4.log 2>&1
- travis_wait 60 bash ./toolchain.sh 5 > /tmp/PS2TOOLCHAIN5.log 2>&1
- cd $TRAVIS_BUILD_DIR
- git clone https://github.com/ps2dev/ps2sdk-ports.git
- cd ps2sdk-ports/libjpeg
- make install
- cd $TRAVIS_BUILD_DIR
- export GSKIT=${PS2DEV}/gsKit
- git clone https://github.com/ps2dev/gsKit.git
- cd gsKit/
- bash ./setup.sh
- cd $TRAVIS_BUILD_DIR
- git clone https://github.com/ps2dev/ps2-packer.git
- cd ps2-packer
- make install

script:
- cd $TRAVIS_BUILD_DIR
- make
